//
//  Copyright 2019 ShortcutRecorder Contributors
//  CC BY 4.0
//

import XCTest

import ShortcutRecorder


class SRKeyCodeTransformerTests: XCTestCase {
    func testUserInterfaceLayoutAltersTabRendering() {
        let c = RecorderControl(frame: .zero)
        c.stringValueRespectsUserInterfaceLayoutDirection = true
        c.drawsASCIIEquivalentOfShortcut = true

        c.userInterfaceLayoutDirection = .leftToRight
        c.objectValue = Shortcut(code: UInt16(kVK_Tab), modifierFlags: [], characters: nil, charactersIgnoringModifiers: nil)
        XCTAssertEqual(c.stringValue, "\u{21E5}")

        c.userInterfaceLayoutDirection = .rightToLeft
        c.objectValue = Shortcut(code: UInt16(kVK_Tab), modifierFlags: [], characters: nil, charactersIgnoringModifiers: nil)
        XCTAssertEqual(c.stringValue, "\u{21E4}")
    }
}


class SRASCIILiteralKeyCodeTransformerTests: XCTestCase {
    func testTransform() {
        func AssertEqual(code: Int, literal: String) {
            XCTContext.runActivity(named: literal) { (_) in
                XCTAssertEqual(ASCIILiteralKeyCodeTransformer.shared.transformedValue(code as NSNumber), literal)
            }
        }

        AssertEqual(code: kVK_ANSI_0, literal: "0")
        AssertEqual(code: kVK_ANSI_1, literal: "1")
        AssertEqual(code: kVK_ANSI_2, literal: "2")
        AssertEqual(code: kVK_ANSI_3, literal: "3")
        AssertEqual(code: kVK_ANSI_4, literal: "4")
        AssertEqual(code: kVK_ANSI_5, literal: "5")
        AssertEqual(code: kVK_ANSI_6, literal: "6")
        AssertEqual(code: kVK_ANSI_7, literal: "7")
        AssertEqual(code: kVK_ANSI_8, literal: "8")
        AssertEqual(code: kVK_ANSI_9, literal: "9")
        AssertEqual(code: kVK_ANSI_A, literal: "A")
        AssertEqual(code: kVK_ANSI_B, literal: "B")
        AssertEqual(code: kVK_ANSI_Backslash, literal: #"\"#)
        AssertEqual(code: kVK_ANSI_C, literal: "C")
        AssertEqual(code: kVK_ANSI_Comma, literal: ",")
        AssertEqual(code: kVK_ANSI_D, literal: "D")
        AssertEqual(code: kVK_ANSI_E, literal: "E")
        AssertEqual(code: kVK_ANSI_Equal, literal: "=")
        AssertEqual(code: kVK_ANSI_F, literal: "F")
        AssertEqual(code: kVK_ANSI_G, literal: "G")
        AssertEqual(code: kVK_ANSI_Grave, literal: "`")
        AssertEqual(code: kVK_ANSI_H, literal: "H")
        AssertEqual(code: kVK_ANSI_I, literal: "I")
        AssertEqual(code: kVK_ANSI_J, literal: "J")
        AssertEqual(code: kVK_ANSI_K, literal: "K")
        AssertEqual(code: kVK_ANSI_Keypad0, literal: "0")
        AssertEqual(code: kVK_ANSI_Keypad1, literal: "1")
        AssertEqual(code: kVK_ANSI_Keypad2, literal: "2")
        AssertEqual(code: kVK_ANSI_Keypad3, literal: "3")
        AssertEqual(code: kVK_ANSI_Keypad4, literal: "4")
        AssertEqual(code: kVK_ANSI_Keypad5, literal: "5")
        AssertEqual(code: kVK_ANSI_Keypad6, literal: "6")
        AssertEqual(code: kVK_ANSI_Keypad7, literal: "7")
        AssertEqual(code: kVK_ANSI_Keypad8, literal: "8")
        AssertEqual(code: kVK_ANSI_Keypad9, literal: "9")
        AssertEqual(code: kVK_ANSI_KeypadDecimal, literal: ".")
        AssertEqual(code: kVK_ANSI_KeypadDivide, literal: "/")
        AssertEqual(code: kVK_ANSI_KeypadEnter, literal: KeyCodeString.return.rawValue)
        AssertEqual(code: kVK_ANSI_KeypadEquals, literal: "=")
        AssertEqual(code: kVK_ANSI_KeypadMinus, literal: "-")
        AssertEqual(code: kVK_ANSI_KeypadMultiply, literal: "*")
        AssertEqual(code: kVK_ANSI_KeypadPlus, literal: "+")
        AssertEqual(code: kVK_ANSI_L, literal: "L")
        AssertEqual(code: kVK_ANSI_LeftBracket, literal: "[")
        AssertEqual(code: kVK_ANSI_M, literal: "M")
        AssertEqual(code: kVK_ANSI_Minus, literal: "-")
        AssertEqual(code: kVK_ANSI_N, literal: "N")
        AssertEqual(code: kVK_ANSI_O, literal: "O")
        AssertEqual(code: kVK_ANSI_P, literal: "P")
        AssertEqual(code: kVK_ANSI_Period, literal: ".")
        AssertEqual(code: kVK_ANSI_Q, literal: "Q")
        AssertEqual(code: kVK_ANSI_Quote, literal: "'")
        AssertEqual(code: kVK_ANSI_R, literal: "R")
        AssertEqual(code: kVK_ANSI_RightBracket, literal: "]")
        AssertEqual(code: kVK_ANSI_S, literal: "S")
        AssertEqual(code: kVK_ANSI_Semicolon, literal: ";")
        AssertEqual(code: kVK_ANSI_Slash, literal: "/")
        AssertEqual(code: kVK_ANSI_T, literal: "T")
        AssertEqual(code: kVK_ANSI_U, literal: "U")
        AssertEqual(code: kVK_ANSI_V, literal: "V")
        AssertEqual(code: kVK_ANSI_W, literal: "W")
        AssertEqual(code: kVK_ANSI_X, literal: "X")
        AssertEqual(code: kVK_ANSI_Y, literal: "Y")
        AssertEqual(code: kVK_ANSI_Z, literal: "Z")
        AssertEqual(code: kVK_Delete, literal: KeyCodeString.deleteLeft.rawValue)
        AssertEqual(code: kVK_DownArrow, literal: KeyCodeString.downArrow.rawValue)
        AssertEqual(code: kVK_End, literal: KeyCodeString.southeastArrow.rawValue)
        AssertEqual(code: kVK_Escape, literal: KeyCodeString.escape.rawValue)
        AssertEqual(code: kVK_F1, literal: "F1")
        AssertEqual(code: kVK_F2, literal: "F2")
        AssertEqual(code: kVK_F3, literal: "F3")
        AssertEqual(code: kVK_F4, literal: "F4")
        AssertEqual(code: kVK_F5, literal: "F5")
        AssertEqual(code: kVK_F6, literal: "F6")
        AssertEqual(code: kVK_F7, literal: "F7")
        AssertEqual(code: kVK_F8, literal: "F8")
        AssertEqual(code: kVK_F9, literal: "F9")
        AssertEqual(code: kVK_F10, literal: "F10")
        AssertEqual(code: kVK_F11, literal: "F11")
        AssertEqual(code: kVK_F12, literal: "F12")
        AssertEqual(code: kVK_F13, literal: "F13")
        AssertEqual(code: kVK_F14, literal: "F14")
        AssertEqual(code: kVK_F15, literal: "F15")
        AssertEqual(code: kVK_F16, literal: "F16")
        AssertEqual(code: kVK_F17, literal: "F17")
        AssertEqual(code: kVK_F18, literal: "F18")
        AssertEqual(code: kVK_F19, literal: "F19")
        AssertEqual(code: kVK_F20, literal: "F20")
        AssertEqual(code: kVK_ForwardDelete, literal: KeyCodeString.deleteRight.rawValue)
        AssertEqual(code: kVK_Help, literal: KeyCodeString.help.rawValue)
        AssertEqual(code: kVK_Home, literal: KeyCodeString.northwestArrow.rawValue)
        AssertEqual(code: kVK_ISO_Section, literal: "§")
        AssertEqual(code: kVK_JIS_KeypadComma, literal: KeyCodeString.jisComma.rawValue)
        AssertEqual(code: kVK_JIS_Underscore, literal: KeyCodeString.jisUnderscore.rawValue)
        AssertEqual(code: kVK_JIS_Yen, literal: KeyCodeString.jisYen.rawValue)
        AssertEqual(code: kVK_LeftArrow, literal: KeyCodeString.leftArrow.rawValue)
        AssertEqual(code: kVK_PageDown, literal: KeyCodeString.pageDown.rawValue)
        AssertEqual(code: kVK_PageUp, literal: KeyCodeString.pageUp.rawValue)
        AssertEqual(code: kVK_Return, literal: KeyCodeString.returnR2L.rawValue)
        AssertEqual(code: kVK_RightArrow, literal: KeyCodeString.rightArrow.rawValue)
        AssertEqual(code: kVK_Space, literal: shortcutRecorderLocalizedString(forKey: "Space"))
        AssertEqual(code: kVK_Tab, literal: KeyCodeString.tabRight.rawValue)
        AssertEqual(code: kVK_UpArrow, literal: KeyCodeString.upArrow.rawValue)
    }

    func testReverseTransform() {
        func AssertEqual(literal: String, code: Int) {
            XCTContext.runActivity(named: literal) { (_) in
                XCTAssertEqual(ASCIILiteralKeyCodeTransformer.shared.reverseTransformedValue(literal) as! Int, code)
            }
        }

        AssertEqual(literal: "0", code: kVK_ANSI_0)
        AssertEqual(literal: "1", code: kVK_ANSI_1)
        AssertEqual(literal: "2", code: kVK_ANSI_2)
        AssertEqual(literal: "3", code: kVK_ANSI_3)
        AssertEqual(literal: "4", code: kVK_ANSI_4)
        AssertEqual(literal: "5", code: kVK_ANSI_5)
        AssertEqual(literal: "6", code: kVK_ANSI_6)
        AssertEqual(literal: "7", code: kVK_ANSI_7)
        AssertEqual(literal: "8", code: kVK_ANSI_8)
        AssertEqual(literal: "9", code: kVK_ANSI_9)
        AssertEqual(literal: "a", code: kVK_ANSI_A)
        AssertEqual(literal: "A", code: kVK_ANSI_A)
        AssertEqual(literal: "b", code: kVK_ANSI_B)
        AssertEqual(literal: #"\"#, code: kVK_ANSI_Backslash)
        AssertEqual(literal: "c", code: kVK_ANSI_C)
        AssertEqual(literal: ",", code: kVK_ANSI_Comma)
        AssertEqual(literal: "d", code: kVK_ANSI_D)
        AssertEqual(literal: "e", code: kVK_ANSI_E)
        AssertEqual(literal: "=", code: kVK_ANSI_Equal)
        AssertEqual(literal: "f", code: kVK_ANSI_F)
        AssertEqual(literal: "g", code: kVK_ANSI_G)
        AssertEqual(literal: "`", code: kVK_ANSI_Grave)
        AssertEqual(literal: "h", code: kVK_ANSI_H)
        AssertEqual(literal: "i", code: kVK_ANSI_I)
        AssertEqual(literal: "j", code: kVK_ANSI_J)
        AssertEqual(literal: "k", code: kVK_ANSI_K)
        AssertEqual(literal: "⌅", code: kVK_ANSI_KeypadEnter)
        AssertEqual(literal: "l", code: kVK_ANSI_L)
        AssertEqual(literal: "[", code: kVK_ANSI_LeftBracket)
        AssertEqual(literal: "m", code: kVK_ANSI_M)
        AssertEqual(literal: "-", code: kVK_ANSI_Minus)
        AssertEqual(literal: "n", code: kVK_ANSI_N)
        AssertEqual(literal: "o", code: kVK_ANSI_O)
        AssertEqual(literal: "p", code: kVK_ANSI_P)
        AssertEqual(literal: ".", code: kVK_ANSI_Period)
        AssertEqual(literal: "q", code: kVK_ANSI_Q)
        AssertEqual(literal: "'", code: kVK_ANSI_Quote)
        AssertEqual(literal: "r", code: kVK_ANSI_R)
        AssertEqual(literal: "]", code: kVK_ANSI_RightBracket)
        AssertEqual(literal: "s", code: kVK_ANSI_S)
        AssertEqual(literal: ";", code: kVK_ANSI_Semicolon)
        AssertEqual(literal: "/", code: kVK_ANSI_Slash)
        AssertEqual(literal: "t", code: kVK_ANSI_T)
        AssertEqual(literal: "u", code: kVK_ANSI_U)
        AssertEqual(literal: "v", code: kVK_ANSI_V)
        AssertEqual(literal: "w", code: kVK_ANSI_W)
        AssertEqual(literal: "x", code: kVK_ANSI_X)
        AssertEqual(literal: "y", code: kVK_ANSI_Y)
        AssertEqual(literal: "z", code: kVK_ANSI_Z)
        AssertEqual(literal: "⌫", code: kVK_Delete)
        AssertEqual(literal: "↓", code: kVK_DownArrow)
        AssertEqual(literal: "↘", code: kVK_End)
        AssertEqual(literal: "⎋", code: kVK_Escape)
        AssertEqual(literal: "Esc", code: kVK_Escape)
        AssertEqual(literal: "Escape", code: kVK_Escape)
        AssertEqual(literal: "F1", code: kVK_F1)
        AssertEqual(literal: "f1", code: kVK_F1)
        AssertEqual(literal: "F2", code: kVK_F2)
        AssertEqual(literal: "F3", code: kVK_F3)
        AssertEqual(literal: "F4", code: kVK_F4)
        AssertEqual(literal: "F5", code: kVK_F5)
        AssertEqual(literal: "F6", code: kVK_F6)
        AssertEqual(literal: "F7", code: kVK_F7)
        AssertEqual(literal: "F8", code: kVK_F8)
        AssertEqual(literal: "F9", code: kVK_F9)
        AssertEqual(literal: "F10", code: kVK_F10)
        AssertEqual(literal: "F11", code: kVK_F11)
        AssertEqual(literal: "F12", code: kVK_F12)
        AssertEqual(literal: "F13", code: kVK_F13)
        AssertEqual(literal: "F14", code: kVK_F14)
        AssertEqual(literal: "F15", code: kVK_F15)
        AssertEqual(literal: "F16", code: kVK_F16)
        AssertEqual(literal: "F17", code: kVK_F17)
        AssertEqual(literal: "F18", code: kVK_F18)
        AssertEqual(literal: "F19", code: kVK_F19)
        AssertEqual(literal: "F20", code: kVK_F20)
        AssertEqual(literal: "⌦", code: kVK_ForwardDelete)
        AssertEqual(literal: "?⃝", code: kVK_Help)
        AssertEqual(literal: "Help", code: kVK_Help)
        AssertEqual(literal: "↖", code: kVK_Home)
        AssertEqual(literal: "§", code: kVK_ISO_Section)
        AssertEqual(literal: "←", code: kVK_LeftArrow)
        AssertEqual(literal: "⇟", code: kVK_PageDown)
        AssertEqual(literal: "⇞", code: kVK_PageUp)
        AssertEqual(literal: "↩", code: kVK_Return)
        AssertEqual(literal: "Enter", code: kVK_Return)
        AssertEqual(literal: "→", code: kVK_RightArrow)
        AssertEqual(literal: " ", code: kVK_Space)
        AssertEqual(literal: "Space", code: kVK_Space)
        AssertEqual(literal: "⇥", code: kVK_Tab)
        AssertEqual(literal: "⇤", code: kVK_Tab)
        AssertEqual(literal: "Tab", code: kVK_Tab)
        AssertEqual(literal: "↑", code: kVK_UpArrow)
        AssertEqual(literal: "＿", code: kVK_JIS_Underscore)
        AssertEqual(literal: "、", code: kVK_JIS_KeypadComma)
        AssertEqual(literal: "¥", code: kVK_JIS_Yen)
        AssertEqual(literal: "*", code: kVK_ANSI_KeypadMultiply);
        AssertEqual(literal: "+", code: kVK_ANSI_KeypadPlus);
    }
}


class SRASCIISymbolicKeyCodeTransformerTests: XCTestCase {
    func testTransform() {
        func AssertEqual(code: Int, symbol: String) {
            XCTContext.runActivity(named: symbol) { (_) in
                XCTAssertEqual(ASCIISymbolicKeyCodeTransformer.shared.transformedValue(code as NSNumber), symbol)
            }
        }

        AssertEqual(code: kVK_ANSI_0, symbol: "0")
        AssertEqual(code: kVK_ANSI_1, symbol: "1")
        AssertEqual(code: kVK_ANSI_2, symbol: "2")
        AssertEqual(code: kVK_ANSI_3, symbol: "3")
        AssertEqual(code: kVK_ANSI_4, symbol: "4")
        AssertEqual(code: kVK_ANSI_5, symbol: "5")
        AssertEqual(code: kVK_ANSI_6, symbol: "6")
        AssertEqual(code: kVK_ANSI_7, symbol: "7")
        AssertEqual(code: kVK_ANSI_8, symbol: "8")
        AssertEqual(code: kVK_ANSI_9, symbol: "9")
        AssertEqual(code: kVK_ANSI_A, symbol: "a")
        AssertEqual(code: kVK_ANSI_B, symbol: "b")
        AssertEqual(code: kVK_ANSI_Backslash, symbol: #"\"#)
        AssertEqual(code: kVK_ANSI_C, symbol: "c")
        AssertEqual(code: kVK_ANSI_Comma, symbol: ",")
        AssertEqual(code: kVK_ANSI_D, symbol: "d")
        AssertEqual(code: kVK_ANSI_E, symbol: "e")
        AssertEqual(code: kVK_ANSI_Equal, symbol: "=")
        AssertEqual(code: kVK_ANSI_F, symbol: "f")
        AssertEqual(code: kVK_ANSI_G, symbol: "g")
        AssertEqual(code: kVK_ANSI_Grave, symbol: "`")
        AssertEqual(code: kVK_ANSI_H, symbol: "h")
        AssertEqual(code: kVK_ANSI_I, symbol: "i")
        AssertEqual(code: kVK_ANSI_J, symbol: "j")
        AssertEqual(code: kVK_ANSI_K, symbol: "k")
        AssertEqual(code: kVK_ANSI_Keypad0, symbol: "0")
        AssertEqual(code: kVK_ANSI_Keypad1, symbol: "1")
        AssertEqual(code: kVK_ANSI_Keypad2, symbol: "2")
        AssertEqual(code: kVK_ANSI_Keypad3, symbol: "3")
        AssertEqual(code: kVK_ANSI_Keypad4, symbol: "4")
        AssertEqual(code: kVK_ANSI_Keypad5, symbol: "5")
        AssertEqual(code: kVK_ANSI_Keypad6, symbol: "6")
        AssertEqual(code: kVK_ANSI_Keypad7, symbol: "7")
        AssertEqual(code: kVK_ANSI_Keypad8, symbol: "8")
        AssertEqual(code: kVK_ANSI_Keypad9, symbol: "9")
        AssertEqual(code: kVK_ANSI_KeypadDecimal, symbol: ".")
        AssertEqual(code: kVK_ANSI_KeypadDivide, symbol: "/")
        AssertEqual(code: kVK_ANSI_KeypadEnter, symbol: unicharToString(unichar(NSEnterCharacter)))
        AssertEqual(code: kVK_ANSI_KeypadEquals, symbol: "=")
        AssertEqual(code: kVK_ANSI_KeypadMinus, symbol: "-")
        AssertEqual(code: kVK_ANSI_KeypadMultiply, symbol: "*")
        AssertEqual(code: kVK_ANSI_KeypadPlus, symbol: "+")
        AssertEqual(code: kVK_ANSI_L, symbol: "l")
        AssertEqual(code: kVK_ANSI_LeftBracket, symbol: "[")
        AssertEqual(code: kVK_ANSI_M, symbol: "m")
        AssertEqual(code: kVK_ANSI_Minus, symbol: "-")
        AssertEqual(code: kVK_ANSI_N, symbol: "n")
        AssertEqual(code: kVK_ANSI_O, symbol: "o")
        AssertEqual(code: kVK_ANSI_P, symbol: "p")
        AssertEqual(code: kVK_ANSI_Period, symbol: ".")
        AssertEqual(code: kVK_ANSI_Q, symbol: "q")
        AssertEqual(code: kVK_ANSI_Quote, symbol: "'")
        AssertEqual(code: kVK_ANSI_R, symbol: "r")
        AssertEqual(code: kVK_ANSI_RightBracket, symbol: "]")
        AssertEqual(code: kVK_ANSI_S, symbol: "s")
        AssertEqual(code: kVK_ANSI_Semicolon, symbol: ";")
        AssertEqual(code: kVK_ANSI_Slash, symbol: "/")
        AssertEqual(code: kVK_ANSI_T, symbol: "t")
        AssertEqual(code: kVK_ANSI_U, symbol: "u")
        AssertEqual(code: kVK_ANSI_V, symbol: "v")
        AssertEqual(code: kVK_ANSI_W, symbol: "w")
        AssertEqual(code: kVK_ANSI_X, symbol: "x")
        AssertEqual(code: kVK_ANSI_Y, symbol: "y")
        AssertEqual(code: kVK_ANSI_Z, symbol: "z")
        AssertEqual(code: kVK_Delete, symbol: unicharToString(unichar(NSBackspaceCharacter)))
        AssertEqual(code: kVK_DownArrow, symbol: unicharToString(unichar(NSDownArrowFunctionKey)))
        AssertEqual(code: kVK_End, symbol: unicharToString(unichar(NSEndFunctionKey)))
        AssertEqual(code: kVK_Escape, symbol: "\u{1b}")
        AssertEqual(code: kVK_F1, symbol: unicharToString(unichar(NSF1FunctionKey)))
        AssertEqual(code: kVK_F2, symbol: unicharToString(unichar(NSF2FunctionKey)))
        AssertEqual(code: kVK_F3, symbol: unicharToString(unichar(NSF3FunctionKey)))
        AssertEqual(code: kVK_F4, symbol: unicharToString(unichar(NSF4FunctionKey)))
        AssertEqual(code: kVK_F5, symbol: unicharToString(unichar(NSF5FunctionKey)))
        AssertEqual(code: kVK_F6, symbol: unicharToString(unichar(NSF6FunctionKey)))
        AssertEqual(code: kVK_F7, symbol: unicharToString(unichar(NSF7FunctionKey)))
        AssertEqual(code: kVK_F8, symbol: unicharToString(unichar(NSF8FunctionKey)))
        AssertEqual(code: kVK_F9, symbol: unicharToString(unichar(NSF9FunctionKey)))
        AssertEqual(code: kVK_F10, symbol: unicharToString(unichar(NSF10FunctionKey)))
        AssertEqual(code: kVK_F11, symbol: unicharToString(unichar(NSF11FunctionKey)))
        AssertEqual(code: kVK_F12, symbol: unicharToString(unichar(NSF12FunctionKey)))
        AssertEqual(code: kVK_F13, symbol: unicharToString(unichar(NSF13FunctionKey)))
        AssertEqual(code: kVK_F14, symbol: unicharToString(unichar(NSF14FunctionKey)))
        AssertEqual(code: kVK_F15, symbol: unicharToString(unichar(NSF15FunctionKey)))
        AssertEqual(code: kVK_F16, symbol: unicharToString(unichar(NSF16FunctionKey)))
        AssertEqual(code: kVK_F17, symbol: unicharToString(unichar(NSF17FunctionKey)))
        AssertEqual(code: kVK_F18, symbol: unicharToString(unichar(NSF18FunctionKey)))
        AssertEqual(code: kVK_F19, symbol: unicharToString(unichar(NSF19FunctionKey)))
        AssertEqual(code: kVK_F20, symbol: unicharToString(unichar(NSF20FunctionKey)))
        AssertEqual(code: kVK_ForwardDelete, symbol: unicharToString(unichar(NSDeleteCharacter)))
        AssertEqual(code: kVK_Help, symbol: unicharToString(unichar(NSHelpFunctionKey)))
        AssertEqual(code: kVK_Home, symbol: unicharToString(unichar(NSHomeFunctionKey)))
        AssertEqual(code: kVK_ISO_Section, symbol: "§")
        AssertEqual(code: kVK_JIS_KeypadComma, symbol: KeyCodeString.jisComma.rawValue)
        AssertEqual(code: kVK_JIS_Underscore, symbol: KeyCodeString.jisUnderscore.rawValue)
        AssertEqual(code: kVK_JIS_Yen, symbol: KeyCodeString.jisYen.rawValue)
        AssertEqual(code: kVK_LeftArrow, symbol: unicharToString(unichar(NSLeftArrowFunctionKey)))
        AssertEqual(code: kVK_PageDown, symbol: unicharToString(unichar(NSPageDownFunctionKey)))
        AssertEqual(code: kVK_PageUp, symbol: unicharToString(unichar(NSPageUpFunctionKey)))
        AssertEqual(code: kVK_Return, symbol: unicharToString(unichar(NSCarriageReturnCharacter)))
        AssertEqual(code: kVK_RightArrow, symbol: unicharToString(unichar(NSRightArrowFunctionKey)))
        AssertEqual(code: kVK_Space, symbol: " ")
        AssertEqual(code: kVK_Tab, symbol: unicharToString(unichar(NSTabCharacter)))
        AssertEqual(code: kVK_UpArrow, symbol: unicharToString(unichar(NSUpArrowFunctionKey)))
    }

    func testReverseTransform() {
        func AssertEqual(symbol: String, code: Int) {
            XCTContext.runActivity(named: symbol) { (_) in
                XCTAssertEqual(ASCIISymbolicKeyCodeTransformer.shared.reverseTransformedValue(symbol) as! Int, code)
            }
        }

        AssertEqual(symbol: "0", code: kVK_ANSI_0)
        AssertEqual(symbol: "1", code: kVK_ANSI_1)
        AssertEqual(symbol: "2", code: kVK_ANSI_2)
        AssertEqual(symbol: "3", code: kVK_ANSI_3)
        AssertEqual(symbol: "4", code: kVK_ANSI_4)
        AssertEqual(symbol: "5", code: kVK_ANSI_5)
        AssertEqual(symbol: "6", code: kVK_ANSI_6)
        AssertEqual(symbol: "7", code: kVK_ANSI_7)
        AssertEqual(symbol: "8", code: kVK_ANSI_8)
        AssertEqual(symbol: "9", code: kVK_ANSI_9)
        AssertEqual(symbol: "a", code: kVK_ANSI_A)
        AssertEqual(symbol: "A", code: kVK_ANSI_A)
        AssertEqual(symbol: "b", code: kVK_ANSI_B)
        AssertEqual(symbol: #"\"#, code: kVK_ANSI_Backslash)
        AssertEqual(symbol: "c", code: kVK_ANSI_C)
        AssertEqual(symbol: ",", code: kVK_ANSI_Comma)
        AssertEqual(symbol: "d", code: kVK_ANSI_D)
        AssertEqual(symbol: "e", code: kVK_ANSI_E)
        AssertEqual(symbol: "=", code: kVK_ANSI_Equal)
        AssertEqual(symbol: "f", code: kVK_ANSI_F)
        AssertEqual(symbol: "g", code: kVK_ANSI_G)
        AssertEqual(symbol: "`", code: kVK_ANSI_Grave)
        AssertEqual(symbol: "h", code: kVK_ANSI_H)
        AssertEqual(symbol: "i", code: kVK_ANSI_I)
        AssertEqual(symbol: "j", code: kVK_ANSI_J)
        AssertEqual(symbol: "k", code: kVK_ANSI_K)
        AssertEqual(symbol: unicharToString(unichar(NSEnterCharacter)), code: kVK_ANSI_KeypadEnter)
        AssertEqual(symbol: "l", code: kVK_ANSI_L)
        AssertEqual(symbol: "[", code: kVK_ANSI_LeftBracket)
        AssertEqual(symbol: "m", code: kVK_ANSI_M)
        AssertEqual(symbol: "-", code: kVK_ANSI_Minus)
        AssertEqual(symbol: "n", code: kVK_ANSI_N)
        AssertEqual(symbol: "o", code: kVK_ANSI_O)
        AssertEqual(symbol: "p", code: kVK_ANSI_P)
        AssertEqual(symbol: ".", code: kVK_ANSI_Period)
        AssertEqual(symbol: "q", code: kVK_ANSI_Q)
        AssertEqual(symbol: "'", code: kVK_ANSI_Quote)
        AssertEqual(symbol: "r", code: kVK_ANSI_R)
        AssertEqual(symbol: "]", code: kVK_ANSI_RightBracket)
        AssertEqual(symbol: "s", code: kVK_ANSI_S)
        AssertEqual(symbol: ";", code: kVK_ANSI_Semicolon)
        AssertEqual(symbol: "/", code: kVK_ANSI_Slash)
        AssertEqual(symbol: "t", code: kVK_ANSI_T)
        AssertEqual(symbol: "u", code: kVK_ANSI_U)
        AssertEqual(symbol: "v", code: kVK_ANSI_V)
        AssertEqual(symbol: "w", code: kVK_ANSI_W)
        AssertEqual(symbol: "x", code: kVK_ANSI_X)
        AssertEqual(symbol: "y", code: kVK_ANSI_Y)
        AssertEqual(symbol: "z", code: kVK_ANSI_Z)
        AssertEqual(symbol: unicharToString(unichar(NSBackspaceCharacter)), code: kVK_Delete)
        AssertEqual(symbol: unicharToString(unichar(NSDownArrowFunctionKey)), code: kVK_DownArrow)
        AssertEqual(symbol: unicharToString(unichar(NSEndFunctionKey)), code: kVK_End)
        AssertEqual(symbol: "\u{1b}", code: kVK_Escape)
        AssertEqual(symbol: unicharToString(unichar(NSF1FunctionKey)), code: kVK_F1)
        AssertEqual(symbol: unicharToString(unichar(NSF2FunctionKey)), code: kVK_F2)
        AssertEqual(symbol: unicharToString(unichar(NSF3FunctionKey)), code: kVK_F3)
        AssertEqual(symbol: unicharToString(unichar(NSF4FunctionKey)), code: kVK_F4)
        AssertEqual(symbol: unicharToString(unichar(NSF5FunctionKey)), code: kVK_F5)
        AssertEqual(symbol: unicharToString(unichar(NSF6FunctionKey)), code: kVK_F6)
        AssertEqual(symbol: unicharToString(unichar(NSF7FunctionKey)), code: kVK_F7)
        AssertEqual(symbol: unicharToString(unichar(NSF8FunctionKey)), code: kVK_F8)
        AssertEqual(symbol: unicharToString(unichar(NSF9FunctionKey)), code: kVK_F9)
        AssertEqual(symbol: unicharToString(unichar(NSF10FunctionKey)), code: kVK_F10)
        AssertEqual(symbol: unicharToString(unichar(NSF11FunctionKey)), code: kVK_F11)
        AssertEqual(symbol: unicharToString(unichar(NSF12FunctionKey)), code: kVK_F12)
        AssertEqual(symbol: unicharToString(unichar(NSF13FunctionKey)), code: kVK_F13)
        AssertEqual(symbol: unicharToString(unichar(NSF14FunctionKey)), code: kVK_F14)
        AssertEqual(symbol: unicharToString(unichar(NSF15FunctionKey)), code: kVK_F15)
        AssertEqual(symbol: unicharToString(unichar(NSF16FunctionKey)), code: kVK_F16)
        AssertEqual(symbol: unicharToString(unichar(NSF17FunctionKey)), code: kVK_F17)
        AssertEqual(symbol: unicharToString(unichar(NSF18FunctionKey)), code: kVK_F18)
        AssertEqual(symbol: unicharToString(unichar(NSF19FunctionKey)), code: kVK_F19)
        AssertEqual(symbol: unicharToString(unichar(NSF20FunctionKey)), code: kVK_F20)
        AssertEqual(symbol: unicharToString(unichar(NSDeleteCharacter)), code: kVK_ForwardDelete)
        AssertEqual(symbol: unicharToString(unichar(NSHelpFunctionKey)), code: kVK_Help)
        AssertEqual(symbol: unicharToString(unichar(NSHomeFunctionKey)), code: kVK_Home)
        AssertEqual(symbol: "§", code: kVK_ISO_Section)
        AssertEqual(symbol: unicharToString(unichar(NSLeftArrowFunctionKey)), code: kVK_LeftArrow)
        AssertEqual(symbol: unicharToString(unichar(NSPageDownFunctionKey)), code: kVK_PageDown)
        AssertEqual(symbol: unicharToString(unichar(NSPageUpFunctionKey)), code: kVK_PageUp)
        AssertEqual(symbol: unicharToString(unichar(NSCarriageReturnCharacter)), code: kVK_Return)
        AssertEqual(symbol: unicharToString(unichar(NSRightArrowFunctionKey)), code: kVK_RightArrow)
        AssertEqual(symbol: " ", code: kVK_Space)
        AssertEqual(symbol: unicharToString(unichar(NSTabCharacter)), code: kVK_Tab)
        AssertEqual(symbol: unicharToString(unichar(NSBackTabCharacter)), code: kVK_Tab)
        AssertEqual(symbol: unicharToString(unichar(NSUpArrowFunctionKey)), code: kVK_UpArrow)
        AssertEqual(symbol: "＿", code: kVK_JIS_Underscore)
        AssertEqual(symbol: "、", code: kVK_JIS_KeypadComma)
        AssertEqual(symbol: "¥", code: kVK_JIS_Yen)
        AssertEqual(symbol: "*", code: kVK_ANSI_KeypadMultiply);
        AssertEqual(symbol: "+", code: kVK_ANSI_KeypadPlus);
    }
}
